version: '2'

services:
  bot:
    build: bot/.
    image: thekevjames/jarvis
    environment:
      - MAILGUN_API_KEY=${MAILGUN_API_KEY}
      - SENTRY_DSN=${SENTRY_DSN_JARVIS}
      - SLACK_TOKEN=${SLACK_TOKEN}
      - TORRENTDAY_COOKIE=${TORRENTDAY_COOKIE}
      - WORLD_WEATHER_TOKEN=${WORLD_WEATHER_TOKEN}
    ports:
      - "28007:8080"
    volumes:
      - ./db:/db
